// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iseemjooeveamnkknijs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZWVtam9vZXZlYW1ua2tuaWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzQ3ODcsImV4cCI6MjA1ODE1MDc4N30.gmDOzyAattG0ZVIiHzktF70V0dMAeiPAesxmRHJmAx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);