// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkhotagfyeqyqtykgzrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraG90YWdmeWVxeXF0eWtnenJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDIyNDYsImV4cCI6MjA2MDkxODI0Nn0.0HT77VZcvYbwB_FTLdc2bKdq6jk3On0OdiSOIB-QpHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);